### ISSUE TITLE
revise against solid spec

### ISSUE THREAD

**Issue by chicco785** [orchestracities/anubis#8]
**Is your feature request related to a problem? Please describe.**

The existing implementation should be revise against SOLID WAC specs.

**Describe the solution you'd like**

The concept was developed based on https://solid.github.io/web-access-control-spec/
but not fully aligned, should we align to this, what's missing? what are the steps needed?

For each element an issue should be opened.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Cerfoglg** [comment]
Looking through the specifications we have:

- **Container resource and root container**: Essentially used to create a hierarchy for resources. Right now we only have the resource defined by itself. This also enables the use of the `acl:accessTo` and `acl:default` predicates to point to a specific resource, or a higher point in the hierarchy. Might be worth considering.
- **Origin**: There is a type of access, defined with `acl:origin`, that allows for access to be granted based on the origin on the HTTP requests, rather than a specific agent/group/role
- **Resource discovery**: See the 3.1 section of the WAC document. It describes how clients could discover the ACL resource associated with a URI by making a request to the server. Not sure how this could translate in our case. We might not want to let clients know exactly what you need to access a resource if this is the implication.

**Comment by chicco785** [comment]
> Looking through the specifications we have:
> 
> * **Container resource and root container**: Essentially used to create a hierarchy for resources. Right now we only have the resource defined by itself. This also enables the use of the `acl:accessTo` and `acl:default` predicates to point to a specific resource, or a higher point in the hierarchy. Might be worth considering.

can't the servicePath be somehow our resource container?

> * **Origin**: There is a type of access, defined with `acl:origin`, that allows for access to be granted based on the origin on the HTTP requests, rather than a specific agent/group/role
> * **Resource discovery**: See the 3.1 section of the WAC document. It describes how clients could discover the ACL resource associated with a URI by making a request to the server. Not sure how this could translate in our case. We might not want to let clients know exactly what you need to access a resource if this is the implication.

**Comment by chicco785** [comment]
see also #43 in relation to correct spec implementation

**Comment by Cerfoglg** [comment]
@chicco785 I believe this issue can be closed, as we have other issues to cover the other acl related functionalities left to implement

**Comment by chicco785** [comment]
> @chicco785 I believe this issue can be closed, as we have other issues to cover the other acl related functionalities left to implement

agree, the only thing left is `origin` support, but a separate issue is open for it
